CREATE DATABASE BRASFOOD 
GO
USE BRASFOOD
GO

CREATE TABLE Usuarios 
(
	IDUser INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Sobrenome VARCHAR(200) NOT NULL,
	DataNascimento DATE NOT NULL,
	Sexo CHAR(20) NOT NULL,
	Telefone CHAR(18) NOT NULL,
	Email VARCHAR(150) NOT NULL,
	Senha VARBINARY(16) NOT NULL
)
CREATE TABLE Post 
(
	IDPost INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	UrlObjeto  VARCHAR (1000), 
	Legenda VARCHAR (3000),
	IDUser INT FOREIGN KEY REFERENCES Usuarios (IDUser),
	DataPost DATE NOT NULL
)
CREATE TABLE Comentarios
(
	IDComent INT  PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Comentario VARCHAR (5000) NOT NULL,
	DataComentario DATE NOT NULL,
	IDUser INT FOREIGN KEY REFERENCES Usuarios (IDUser)
)
CREATE TABLE Feed
(
	IDFeed INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	UrlFeed VARCHAR(100), 
	IDUser INT NOT NULL FOREIGN KEY REFERENCES Usuarios (IDUser),
	IDPost INT NOT NULL FOREIGN KEY REFERENCES Post (IDPost) 
) 
CREATE TABLE Perfil 
(
	IDPerfil INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	IDUser INT FOREIGN KEY REFERENCES Post (IDPost),
	UrlFotoPerfil VARCHAR (1000),
	UrlFotoCapa VARCHAR (1000),
	NomeExibicao VARCHAR(250),
	Nivel VARCHAR(100)
)
CREATE TABLE Album
(
	IDAlbum INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NomeAlbum VARCHAR(200) NOT NULL,
	IDUser INT FOREIGN KEY REFERENCES Usuarios (IDUser),
	UrlMidia VARCHAR(1000)
)